In [1]:
import pandas as pd

In [3]:
customer_info = pd.read_csv('customer_info.csv', index_col = False)
# I removed the Unnamed: 0 column because it functioned as a double index and wasn't necessary.
# Remove the 'Unnamed: 0' column if it exists
if 'Unnamed: 0' in customer_info.columns:
    customer_info.drop(columns=['Unnamed: 0'], inplace=True)
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
0,29930,April Clark,female,01/15/1972 02:27 PM,2.0,2.0,1.0,4.0,7789.0,5601.0,...,1894.0,457.0,412.0,428.0,386.0,0.158741,2018.0,NaN,38.721807,-9.125534
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
2,39451,Mary Downing,female,11/13/1989 02:11 PM,2.0,3.0,0.0,7.0,15605.0,4275.0,...,1971.0,920.0,335.0,192.0,319.0,0.101598,2011.0,NaN,38.787126,-9.147077
3,21557,Manuel Kueny,male,08/09/1976 06:23 AM,0.0,0.0,1.0,1.0,13440.0,16366.0,...,785.0,139.0,679.0,270.0,221.0,0.259943,2009.0,NaN,38.741816,-9.159700
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34055,37071,Mary Diaz,female,01/20/1999 06:47 PM,1.0,1.0,0.0,2.0,62321.0,5250.0,...,1687.0,1048.0,379.0,258.0,163.0,0.162331,2018.0,NaN,38.750813,-9.103808
34056,27422,John Gross,male,08/01/1984 07:50 PM,1.0,1.0,0.0,3.0,16084.0,3796.0,...,568.0,949.0,263.0,319.0,379.0,0.614179,2019.0,985393.0,38.745020,-9.169168
34057,39540,Kathleen Harper,female,09/16/2000 07:22 AM,1.0,0.0,1.0,2.0,14631.0,8784.0,...,1472.0,368.0,804.0,110.0,228.0,0.535617,2018.0,NaN,38.767834,-9.172368
34058,18367,Msc. Jenny Landry,female,04/09/1961 10:52 AM,1.0,1.0,1.0,4.0,37420.0,4702.0,...,904.0,1088.0,401.0,376.0,151.0,0.435014,2015.0,953651.0,38.732462,-9.156155
34059,22050,Roy Wilkins,male,03/25/1993 09:59 PM,2.0,1.0,2.0,1.0,8208.0,38.0,...,618.0,309.0,110.0,471.0,85.0,0.535108,2016.0,NaN,38.747424,-9.155726

In [4]:
customer_basket = pd.read_csv('customer_basket.csv')
customer_basket

,invoice_id,list_of_goods,customer_id
0,5062209,"['megaman zero 3', 'energy bar', 'pokemon viol...",4925
1,4272512,"['black beer', 'bramble', 'laptop', 'pokemon v...",19046
2,7121052,"['soup', 'shallot', 'cake', 'fresh bread', 'cr...",10318
3,5847748,"['soup', 'cooking oil', 'cereals', 'oil', 'dog...",27283
4,6336114,"['eggplant', 'mint green tea', 'oil', 'bacon',...",16072
...,...,...,...
99995,5389466,"['frozen smoothie', 'avocado', 'dog food', 'ch...",26170
99996,10387390,"['cake', 'antioxydant juice', 'honey', 'toothp...",19691
99997,7103407,"['candy bars', 'spaghetti', 'oil', 'final fant...",1720
99998,4093515,"['shallot', 'cereals', 'oil', 'deodorant', 'me...",24989
99999,6611217,"['soup', 'napkins', 'pokemon violet', 'ratchet...",482

In [5]:
customer_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34060 entries, 0 to 34059
Data columns (total 25 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_id                              34060 non-null  int64
 1   customer_name                            34060 non-null  object
 2   customer_gender                          34060 non-null  object
 3   customer_birthdate                       33719 non-null  object
 4   kids_home                                33311 non-null  float64
 5   teens_home                               33277 non-null  float64
 6   number_complaints                        33038 non-null  float64
 7   distinct_stores_visited                  33379 non-null  float64
 8   lifetime_spend_groceries                 34060 non-null  float64
 9   lifetime_spend_electronics               34060 non-null  float64
 10  typical_hour                             32698 non-null  float64
 11  lifetime_spend_vegetables                33038 non-null  float64
 12  lifetime_spend_nonalcohol_drinks         34060 non-null  float64
 13  lifetime_spend_alcohol_drinks            33379 non-null  float64
 14  lifetime_spend_meat                      34060 non-null  float64
 15  lifetime_spend_fish                      32357 non-null  float64
 16  lifetime_spend_hygiene                   34060 non-null  float64
 17  lifetime_spend_videogames                34060 non-null  float64
 18  lifetime_spend_petfood                   34060 non-null  float64
 19  lifetime_total_distinct_products         34060 non-null  float64
 20  percentage_of_products_bought_promotion  34060 non-null  float64
 21  year_first_transaction                   34060 non-null  float64
 22  loyalty_card_number                      23152 non-null  float64
 23  latitude                                 34060 non-null  float64
 24  longitude                                34060 non-null  float64
dtypes: float64(21), int64(1), object(3)
memory usage: 6.5+ MB

In [6]:
customer_basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice_id     100000 non-null  int64
 1   list_of_goods  100000 non-null  object
 2   customer_id    100000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 2.3+ MB

In [7]:
# Check for missing values
print(customer_info.isnull().sum())

customer_id                                    0
customer_name                                  0
customer_gender                                0
customer_birthdate                           341
kids_home                                    749
teens_home                                   783
number_complaints                           1022
distinct_stores_visited                      681
lifetime_spend_groceries                       0
lifetime_spend_electronics                     0
typical_hour                                1362
lifetime_spend_vegetables                   1022
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                681
lifetime_spend_meat                            0
lifetime_spend_fish                         1703
lifetime_spend_hygiene                         0
lifetime_spend_videogames                      0
lifetime_spend_petfood                         0
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion        0
year_first_transaction                         0
loyalty_card_number                        10908
latitude                                       0
longitude                                      0
dtype: int64

In [8]:
print(customer_basket.isnull().sum())

invoice_id       0
list_of_goods    0
customer_id      0
dtype: int64

In [9]:
customer_info.dropna(inplace = True)
# it wasn't necessary to drop any rows in customer_basket because it didn't have an missing values

In [10]:
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
1,6813,Bsc. Paul Ketchum,male,07/31/1944 10:53 AM,0.0,1.0,0.0,4.0,8653.0,35.0,...,346.0,394.0,75.0,226.0,73.0,1.227890,2013.0,971840.0,38.734668,-9.163533
4,16415,Phd. Curtis Tharp,male,07/11/1966 08:12 AM,1.0,1.0,1.0,5.0,49250.0,3197.0,...,1492.0,1046.0,112.0,144.0,244.0,0.317822,2012.0,925367.0,38.785921,-9.149221
5,22853,Phd. Nancy Berger,female,03/22/1950 10:13 PM,1.0,1.0,1.0,3.0,26677.0,3412.0,...,48.0,187.0,177.0,352.0,65.0,0.071312,2013.0,908702.0,38.778774,-9.175644
6,994,Phd. Donna Nicoletti,female,01/30/1967 12:33 PM,1.0,1.0,1.0,2.0,13893.0,593.0,...,91.0,230.0,254.0,239.0,56.0,0.080355,2010.0,929774.0,38.784251,-9.193074
7,28952,Roxanne Elder,female,07/19/1993 10:36 AM,1.0,2.0,0.0,3.0,6596.0,434.0,...,353.0,251.0,197.0,186.0,1.0,0.913403,2018.0,979825.0,38.730918,-9.135005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34048,20587,Bsc. Terry Crane,female,11/06/1988 10:32 PM,1.0,1.0,0.0,3.0,78416.0,2967.0,...,2801.0,674.0,752.0,232.0,84.0,0.178283,2016.0,941174.0,38.762047,-9.081122
34051,6000,Phd. Helen Wilkinson,female,01/14/1980 11:23 AM,1.0,0.0,1.0,4.0,9854.0,2834.0,...,972.0,674.0,248.0,299.0,248.0,0.239898,2012.0,911834.0,38.735663,-9.177997
34052,11347,Phd. Taylor Weissgerber,male,03/26/1967 06:59 PM,2.0,0.0,1.0,4.0,24588.0,3529.0,...,1558.0,1702.0,288.0,329.0,80.0,0.788305,2007.0,945413.0,38.753863,-9.120890
34054,27689,Charlotte Banks,female,03/20/1967 01:07 PM,1.0,2.0,0.0,3.0,38853.0,4521.0,...,1135.0,1006.0,524.0,527.0,329.0,0.205564,2010.0,905894.0,38.742335,-9.178790
34056,27422,John Gross,male,08/01/1984 07:50 PM,1.0,1.0,0.0,3.0,16084.0,3796.0,...,568.0,949.0,263.0,319.0,379.0,0.614179,2019.0,985393.0,38.745020,-9.169168

In [11]:
customer_basket

,invoice_id,list_of_goods,customer_id
0,5062209,"['megaman zero 3', 'energy bar', 'pokemon viol...",4925
1,4272512,"['black beer', 'bramble', 'laptop', 'pokemon v...",19046
2,7121052,"['soup', 'shallot', 'cake', 'fresh bread', 'cr...",10318
3,5847748,"['soup', 'cooking oil', 'cereals', 'oil', 'dog...",27283
4,6336114,"['eggplant', 'mint green tea', 'oil', 'bacon',...",16072
...,...,...,...
99995,5389466,"['frozen smoothie', 'avocado', 'dog food', 'ch...",26170
99996,10387390,"['cake', 'antioxydant juice', 'honey', 'toothp...",19691
99997,7103407,"['candy bars', 'spaghetti', 'oil', 'final fant...",1720
99998,4093515,"['shallot', 'cereals', 'oil', 'deodorant', 'me...",24989
99999,6611217,"['soup', 'napkins', 'pokemon violet', 'ratchet...",482

In [12]:
# Remove duplicates
# there was an error when I tried to drop the duplicates for customer_info because it didn't have and duplicate rows.
customer_basket.drop_duplicates(inplace=True)

In [13]:
customer_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18030 entries, 1 to 34056
Data columns (total 25 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customer_id                              18030 non-null  int64
 1   customer_name                            18030 non-null  object
 2   customer_gender                          18030 non-null  object
 3   customer_birthdate                       18030 non-null  object
 4   kids_home                                18030 non-null  float64
 5   teens_home                               18030 non-null  float64
 6   number_complaints                        18030 non-null  float64
 7   distinct_stores_visited                  18030 non-null  float64
 8   lifetime_spend_groceries                 18030 non-null  float64
 9   lifetime_spend_electronics               18030 non-null  float64
 10  typical_hour                             18030 non-null  float64
 11  lifetime_spend_vegetables                18030 non-null  float64
 12  lifetime_spend_nonalcohol_drinks         18030 non-null  float64
 13  lifetime_spend_alcohol_drinks            18030 non-null  float64
 14  lifetime_spend_meat                      18030 non-null  float64
 15  lifetime_spend_fish                      18030 non-null  float64
 16  lifetime_spend_hygiene                   18030 non-null  float64
 17  lifetime_spend_videogames                18030 non-null  float64
 18  lifetime_spend_petfood                   18030 non-null  float64
 19  lifetime_total_distinct_products         18030 non-null  float64
 20  percentage_of_products_bought_promotion  18030 non-null  float64
 21  year_first_transaction                   18030 non-null  float64
 22  loyalty_card_number                      18030 non-null  float64
 23  latitude                                 18030 non-null  float64
 24  longitude                                18030 non-null  float64
dtypes: float64(21), int64(1), object(3)
memory usage: 3.6+ MB

In [14]:
customer_basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 3 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice_id     100000 non-null  int64
 1   list_of_goods  100000 non-null  object
 2   customer_id    100000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 2.3+ MB

In [27]:
# Converting the data types so they are ready for analysis
# Convert data types if necessary
customer_info['customer_birthdate'] = pd.to_datetime(customer_info['customer_birthdate'])

In [31]:
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_alcohol_drinks,lifetime_spend_meat,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number
1,6813,Paul Ketchum,male,1944-07-31 10:53:00,0,1,0,4,8653,35,...,104,741,346,394,75,226,73,1,2013,971840
4,16415,Curtis Tharp,male,1966-07-11 08:12:00,1,1,1,5,49250,3197,...,547,983,1492,1046,112,144,244,0,2012,925367
5,22853,Nancy Berger,female,1950-03-22 22:13:00,1,1,1,3,26677,3412,...,561,2,48,187,177,352,65,0,2013,908702
6,994,Donna Nicoletti,female,1967-01-30 12:33:00,1,1,1,2,13893,593,...,540,29,91,230,254,239,56,0,2010,929774
7,28952,Roxanne Elder,female,1993-07-19 10:36:00,1,2,0,3,6596,434,...,98,664,353,251,197,186,1,0,2018,979825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34048,20587,Terry Crane,female,1988-11-06 22:32:00,1,1,0,3,78416,2967,...,1497,1416,2801,674,752,232,84,0,2016,941174
34051,6000,Helen Wilkinson,female,1980-01-14 11:23:00,1,0,1,4,9854,2834,...,830,910,972,674,248,299,248,0,2012,911834
34052,11347,Taylor Weissgerber,male,1967-03-26 18:59:00,2,0,1,4,24588,3529,...,758,969,1558,1702,288,329,80,0,2007,945413
34054,27689,Charlotte Banks,female,1967-03-20 13:07:00,1,2,0,3,38853,4521,...,1153,1145,1135,1006,524,527,329,0,2010,905894
34056,27422,John Gross,male,1984-08-01 19:50:00,1,1,0,3,16084,3796,...,694,1200,568,949,263,319,379,0,2019,985393

In [32]:
customer_info = customer_info.apply(lambda x: x.astype(int) if x.dtype == float else x)

In [30]:
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_alcohol_drinks,lifetime_spend_meat,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number
1,6813,Paul Ketchum,male,1944-07-31 10:53:00,0,1,0,4,8653,35,...,104,741,346,394,75,226,73,1,2013,971840
4,16415,Curtis Tharp,male,1966-07-11 08:12:00,1,1,1,5,49250,3197,...,547,983,1492,1046,112,144,244,0,2012,925367
5,22853,Nancy Berger,female,1950-03-22 22:13:00,1,1,1,3,26677,3412,...,561,2,48,187,177,352,65,0,2013,908702
6,994,Donna Nicoletti,female,1967-01-30 12:33:00,1,1,1,2,13893,593,...,540,29,91,230,254,239,56,0,2010,929774
7,28952,Roxanne Elder,female,1993-07-19 10:36:00,1,2,0,3,6596,434,...,98,664,353,251,197,186,1,0,2018,979825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34048,20587,Terry Crane,female,1988-11-06 22:32:00,1,1,0,3,78416,2967,...,1497,1416,2801,674,752,232,84,0,2016,941174
34051,6000,Helen Wilkinson,female,1980-01-14 11:23:00,1,0,1,4,9854,2834,...,830,910,972,674,248,299,248,0,2012,911834
34052,11347,Taylor Weissgerber,male,1967-03-26 18:59:00,2,0,1,4,24588,3529,...,758,969,1558,1702,288,329,80,0,2007,945413
34054,27689,Charlotte Banks,female,1967-03-20 13:07:00,1,2,0,3,38853,4521,...,1153,1145,1135,1006,524,527,329,0,2010,905894
34056,27422,John Gross,male,1984-08-01 19:50:00,1,1,0,3,16084,3796,...,694,1200,568,949,263,319,379,0,2019,985393

In [35]:
customer_info["customer_name"] = customer_info["customer_name"].replace({"Phd.": " ", "Bsc.": " ", "Msc": " "}, regex = True)

In [36]:
customer_info

,customer_id,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,...,lifetime_spend_alcohol_drinks,lifetime_spend_meat,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number
1,6813,Paul Ketchum,male,1944-07-31 10:53:00,0,1,0,4,8653,35,...,104,741,346,394,75,226,73,1,2013,971840
4,16415,Curtis Tharp,male,1966-07-11 08:12:00,1,1,1,5,49250,3197,...,547,983,1492,1046,112,144,244,0,2012,925367
5,22853,Nancy Berger,female,1950-03-22 22:13:00,1,1,1,3,26677,3412,...,561,2,48,187,177,352,65,0,2013,908702
6,994,Donna Nicoletti,female,1967-01-30 12:33:00,1,1,1,2,13893,593,...,540,29,91,230,254,239,56,0,2010,929774
7,28952,Roxanne Elder,female,1993-07-19 10:36:00,1,2,0,3,6596,434,...,98,664,353,251,197,186,1,0,2018,979825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34048,20587,Terry Crane,female,1988-11-06 22:32:00,1,1,0,3,78416,2967,...,1497,1416,2801,674,752,232,84,0,2016,941174
34051,6000,Helen Wilkinson,female,1980-01-14 11:23:00,1,0,1,4,9854,2834,...,830,910,972,674,248,299,248,0,2012,911834
34052,11347,Taylor Weissgerber,male,1967-03-26 18:59:00,2,0,1,4,24588,3529,...,758,969,1558,1702,288,329,80,0,2007,945413
34054,27689,Charlotte Banks,female,1967-03-20 13:07:00,1,2,0,3,38853,4521,...,1153,1145,1135,1006,524,527,329,0,2010,905894
34056,27422,John Gross,male,1984-08-01 19:50:00,1,1,0,3,16084,3796,...,694,1200,568,949,263,319,379,0,2019,985393